# Generated by Django 2.1.4 on 2018-12-14 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='writeboard',
            new_name='Post',
        ),
    ]
