# Generated by Django 2.1.4 on 2018-12-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181214_0244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '投稿', 'verbose_name_plural': '投稿'},
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(max_length=140, verbose_name='メッセージ'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
