# Generated by Django 2.1.4 on 2018-12-26 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='good_counts',
        ),
    ]
