# Generated by Django 2.1.4 on 2019-01-23 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20190123_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
        migrations.AddField(
            model_name='good',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Post'),
        ),
    ]
